### ISSUE TITLE
使用pip安装报错

### ISSUE THREAD

**Issue by leeting726** [PyUnit/pyunit-prime#3]
使用pip安装时一开始报错缺少C++环境，安装c++环境后依然报错
 Building wheel for pyunit-prime (setup.py) ... error
 ERROR: Command errored out with exit status 1:
![image](https://user-images.githubusercontent.com/59569629/141236801-548ed2b6-2e7b-4914-84e3-aa2d52c3b11c.png)

**Comment by jtyoui** [comment]
@leeting726 看样子是C的环境有问题，你安装一个MinGW试一下

**Comment by jtyoui** [comment]
@leeting726  
![1636624288(1)](https://user-images.githubusercontent.com/28988355/141277016-acd369c1-0fa9-46fd-b4c4-9674be053ac6.jpg)

**Comment by lawandcs** [comment]
我也是这个问题最后怎么解决的呀

**Comment by leeting726** [comment]
反正装了环境之后还是不行，我改用了gmpy这个库


> 我也是这个问题最后怎么解决的呀

**Comment by jtyoui** [comment]
@lawandcs 看样子是C++的问题。这个是Cython写的

**Comment by jtyoui** [comment]
换成py3.7版本试一下，或者更高的版本

**Comment by lawandcs** [comment]
我用的是python3.10.1版本的，但是不行
